In [1]:
import warnings
warnings.filterwarnings(action='ignore')
import pandas as pd

In [2]:
train_df = pd.read_csv('/content/ratings_train.txt', encoding='utf8', sep='\t')
train_df

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]

In [3]:
test_df = pd.read_csv('/content/ratings_test.txt', encoding='utf8', sep='\t')
test_df

            id                                           document  label
0      6270596                                                굳 ㅋ      1
1      9274899                               GDNTOPCLASSINTHECLUB      0
2      8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4      6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0
...        ...                                                ...    ...
49995  4608761          오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387       의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO      0
49997  9072549                 그림도 좋고 완성도도 높았지만... 보는 내내 불안하게 만든다      0
49998  5802125     절대 봐서는 안 될 영화.. 재미도 없고 기분만 잡치고.. 한 세트장에서 다 해먹네      0
49999  6070594                                         마무리는 또 왜이래      0

[50000 rows x 3 columns]

In [4]:
train_df['label'].value_counts()

label
0    75173
1    74827
Name: count, dtype: int64

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

In [6]:
train_df = train_df[train_df['document'].notnull()]
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 149995 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        149995 non-null  int64
 1   document  149995 non-null  object
 2   label     149995 non-null  int64
dtypes: int64(2), object(1)
memory usage: 4.6+ MB

In [7]:
import re

In [8]:
# document컬럼에 이상한 문자+숫자+기호를 제거하고 싶음.
# 한글이 아니면 다 ""로 바꿔라고 처리하겠음.
train_df['document'] = train_df['document'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]', '', x))
train_df.head()

         id                                           document  label
0   9976970                                  아 더빙 진짜 짜증나네요 목소리      0
1   3819312                         흠포스터보고 초딩영화줄오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                          교도소 이야기구먼 솔직히 재미는 없다평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던...      1

In [9]:
test_df['label'].value_counts()

label
1    25173
0    24827
Name: count, dtype: int64

In [10]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        50000 non-null  int64
 1   document  49997 non-null  object
 2   label     50000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.1+ MB

In [11]:
# not null인 것만 다시 test_df에 넣으세요.
# 한글이 아닌 것은 ""으로 대체(정규식을 사용)

In [12]:
test_df = test_df[test_df['document'].notnull()]
test_df

            id                                           document  label
0      6270596                                                굳 ㅋ      1
1      9274899                               GDNTOPCLASSINTHECLUB      0
2      8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4      6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0
...        ...                                                ...    ...
49995  4608761          오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387       의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO      0
49997  9072549                 그림도 좋고 완성도도 높았지만... 보는 내내 불안하게 만든다      0
49998  5802125     절대 봐서는 안 될 영화.. 재미도 없고 기분만 잡치고.. 한 세트장에서 다 해먹네      0
49999  6070594                                         마무리는 또 왜이래      0

[49997 rows x 3 columns]

In [13]:
test_df['document'] = test_df['document'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
test_df

            id                                    document  label
0      6270596                                         굳 ㅋ      1
1      9274899                                                  0
2      8544678            뭐야 이 평점들은 나쁘진 않지만 점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임 돈주고 보기에는      0
4      6723715   만 아니었어도 별 다섯 개 줬을텐데 왜 로 나와서 제 심기를 불편하게 하죠      0
...        ...                                         ...    ...
49995  4608761   오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387    의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따       0
49997  9072549             그림도 좋고 완성도도 높았지만 보는 내내 불안하게 만든다      0
49998  5802125  절대 봐서는 안 될 영화 재미도 없고 기분만 잡치고 한 세트장에서 다 해먹네      0
49999  6070594                                  마무리는 또 왜이래      0

[49997 rows x 3 columns]

In [ ]:
# 사전을 만들어야한다.
# 자연어를 파이썬에서 인식할 때는 단어별 번호로 인식함.
# 나는 별로 였어라고 했다고 한다면 나는(1), 별로(100) --> 부정사전, 부정이라고 판단

In [15]:
# !pip install konlpy

In [16]:
from konlpy.tag import Okt

okt = Okt()

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [18]:
## 사전을 만들어주고, df의 문장을 원핫인코딩으로 컬럼을 변환시켜 전환해줌.
# 각 단어에 대해 번호를 부여함.(빈도수 + 이상하게자주반복되는여부)
tfidf = TfidfVectorizer(tokenizer= okt.morphs , ngram_range=(1, 2), min_df = 3, max_df = 0.9)
tfidf

TfidfVectorizer(max_df=0.9, min_df=3, ngram_range=(1, 2),
                tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x7bb631c84740>>)

In [19]:
tfidf.fit(train_df['document']) #사전만들어라.

TfidfVectorizer(max_df=0.9, min_df=3, ngram_range=(1, 2),
                tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x7bb631c84740>>)

In [20]:
train_tfidf_df = tfidf.transform(train_df['document'])
train_tfidf_df #사전을 기준으로 어떤 문장들이 왔는지 원핫인코딩으로 컬럼을 증가시켜 표현해라

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2703859 stored elements and shape (149995, 115612)>

In [21]:
train_tfidf_df[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [23]:
train_tfidf_df[:2].toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
tfidf.vocabulary_

{'아': 58182,
 '더빙': 24726,
 '진짜': 99719,
 '짜증나네요': 100691,
 '목소리': 38530,
 '더빙 진짜': 24753,
 '진짜 짜증나네요': 100164,
 '흠': 115208,
 '포스터': 107469,
 '보고': 43831,
 '초딩': 102651,
 '영화': 69408,
 '줄': 97633,
 '오버': 71226,
 '연기': 68399,
 '조차': 95277,
 '가볍지': 2697,
 '않구나': 60917,
 '포스터 보고': 107484,
 '초딩 영화': 102663,
 '영화 줄': 70303,
 '오버 연기': 71233,
 '연기 조차': 68526,
 '너': 17529,
 '무재': 39573,
 '다그': 22186,
 '래서': 31275,
 '보는것을': 44572,
 '추천': 103295,
 '한': 110324,
 '다': 21645,
 '너 무재': 17552,
 '보는것을 추천': 44573,
 '추천 한': 103323,
 '한 다': 110428,
 '교도소': 9434,
 '이야기': 85209,
 '구먼': 9592,
 '솔직히': 53746,
 '재미': 90457,
 '는': 20247,
 '없다': 64345,
 '평점': 107149,
 '조정': 95253,
 '솔직히 재미': 53790,
 '재미 는': 90472,
 '는 없다': 20864,
 '없다 평점': 64452,
 '평점 조정': 107331,
 '사이': 50416,
 '그': 10241,
 '의': 78728,
 '가': 888,
 '돋보였던': 26501,
 '스파이더맨': 55298,
 '에서': 66756,
 '늙어': 21360,
 '했던': 112855,
 '커스틴': 104211,
 '너무나도': 18293,
 '이뻐': 84890,
 '보였다': 45657,
 '그 의': 10426,
 '연기 가': 68403,
 '가 돋보였던': 1218,
 '돋보였던 영화': 26502,
 '가 너무나도': 1121,
 '막': 34374,
 '걸음': 6175,
 '마': 33830,
 '뗀': 30204,
 '세': 52827,
 '부터': 47930,
 '초등학교': 102635,
 '학년': 110277,
 '생인': 51782,
 'ㅋㅋㅋ': 358,
 '별': 43470,
 '반개': 41631,
 '도': 25056,
 '아까': 58418,
 '움': 73981,
 '초등학교 학년': 102639,
 '영화 ㅋㅋㅋ': 69419,
 'ㅋㅋㅋ 별': 390,
 '별 반개': 43500,
 '반개 도': 41634,
 '도 아까': 25500,
 '아까 움': 58420,
 '원작': 74414,
 '긴장감': 13002,
 '을': 77066,
 '제대로': 94600,
 '했다': 112778,
 '원작 의': 74446,
 '의 긴장감': 78926,
 '긴장감 을': 13022,
 '을 제대로': 78197,
 '아깝다': 58506,
 '욕': 73205,
 '나온다': 15636,
 '이응경': 85572,
 '길용우': 13089,
 '연': 68334,
 '기': 12200,
 '생활': 51800,
 '이': 80622,
 '몇': 37966,
 '년': 18825,
 '인지': 86797,
 '정말': 93644,
 '발': 41991,
 '로': 31575,
 '해도': 112051,
 '그것': 10518,
 '보단': 45037,
 '납치': 16680,
 '감금': 3527,
 '만': 34501,
 '반복': 41664,
 '드라마': 27934,
 '가족': 3049,
 '못': 38768,
 '하는': 109154,
 '사람': 50015,
 '모': 38034,
 '엿': 68995,
 '네': 18622,
 '도 아깝다': 25510,
 '욕 나온다': 73215,
 '연 기': 68344,
 '생활 이': 51809,
 '이 몇': 81525,
 '몇 년': 37970,
 '인지 정말': 86862,
 '발 로': 41995,
 '해도 그것': 112054,
 '그것 보단': 10531,
 '납치 감금': 16681,
 '만 반복': 34674,
 '반복 이': 41668,
 '이 드라마': 81292,
 '드라마 는': 27977,
 '는 가족': 20260,
 '가족 도': 3057,
 '도 없다': 25640,
 '없다 연기': 64416,
 '연기 못': 68465,
 '못 하는': 38939,
 '하는 사람': 109252,
 '사람 만': 50033,
 '엿 네': 68999,
 '액션': 61942,
 '없는데도': 64339,
 '있는': 87989,
 '안되는': 60496,
 '액션 이': 62017,
 '재미 있는': 90557,
 '있는 몇': 88030,
 '몇 안되는': 37990,
 '안되는 영화': 60520,
 '왜케': 72729,
 '꽤': 14246,
 '볼': 46252,
 '데': 24905,
 '헐리우드': 113303,
 '식': 56333,
 '너무': 17575,
 '길들여져': 13075,
 '있나': 87968,
 '왜케 평점': 72738,
 '평점 이': 107292,
 '꽤 볼': 14258,
 '볼 만': 46271,
 '만 한': 34938,
 '한 데': 110454,
 '헐리우드 식': 113307,
 '걍': 5268,
 '인피니트': 86909,
 '짱': 100808,
 '이다': 83582,
 '가 짱': 2248,
 '짱 이다': 100845,
 '이다 진짜': 83727,
 '진짜 짱': 100169,
 '볼때': 46362,
 '마다': 33883,
 '죽겠다': 97348,
 '년대': 18910,
 '향수': 113127,
 '자': 88601,
 '극': 11740,
 '허진호': 113258,
 '감성': 3879,
 '절제': 93047,
 '멜로': 37563,
 '달인': 23136,
 '볼때 마다': 46367,
 '년대 의': 18940,
 '의 향수': 80350,
 '는 감성': 20267,
 '멜로 의': 37582,
 '의 달인': 79015,
 '달인 이다': 23137,
 '울면': 73903,
 '서': 51846,
 '손': 53654,
 '들': 28387,
 '고': 7308,
 '때': 29685,
 '뛰': 30438,
 '쳐나': 102567,
 '올': 71484,
 '뻔': 49612,
 '이범수': 84842,
 '드럽게': 28221,
 '해': 111928,
 '울면 서': 73904,
 '들 고': 28423,
 '뛰 쳐나': 30440,
 '쳐나 올': 102568,
 '올 뻔': 71497,
 '이범수 연기': 84844,
 '연기 드럽게': 68438,
 '드럽게 못': 28222,
 '못 해': 38988,
 '담백하고': 23216,
 '깔끔해서': 13810,
 '좋다': 96059,
 '신': 56426,
 '문': 39683,
 '사': 49843,
 '로만': 32174,
 '보다': 44730,
 '보면': 45158,
 '자꾸': 88713,
 '이었다는': 85354,
 '것': 6268,
 '신 문': 56435,
 '기 사': 12247,
 '보다 보면': 44817,
 '그 들': 10301,
 '들 도': 28491,
 '도 사람': 25441,
 '이었다는 것': 85355,
 '것 을': 6354,
 '취향': 103599,
 '은': 76026,
 '존중': 95472,
 '다지': 22753,
 '내생': 17253,
 '에': 64918,
 '극장': 11808,
 '본': 45942,
 '중': 97783,
 '가장': 2922,
 '노잼': 19202,
 '노': 19019,
 '감동': 3674,
 '임': 87455,
 '스토리': 55047,
 '어거지': 62540,
 '취향 은': 103605,
 '은 존중': 76839,
 '한 다지': 110439,
 '다지 만': 22754,
 '만 진짜': 34898,
 '진짜 내생': 99793,
 '내생 에': 17254,
 '에 극장': 65066,
 '극장 에서': 11818,
 '에서 본': 66933,
 '본 영화': 46024,
 '영화 중': 70305,
 '중 가장': 97787,
 '노잼 노': 19210,
 '노 감동': 19021,
 '감동 임': 3773,
 '임 스토리': 87502,
 '스토리 도': 55088,
 '도 어거지': 25599,
 '고 감동': 7324,
 '감동 도': 3699,
 'ㄱ': 0,
 '냥': 17519,
 '매번': 36766,
 '긴장': 12989,
 '되고': 27014,
 '재밋음': 91089,
 'ㅠㅠ': 684,
 '긴장 되고': 12991,
 '재밋음 ㅠㅠ': 91091,
 '참': 101494,
 '웃긴게': 74154,
 '바스코': 41290,
 '이기': 83328,
 '면': 37614,
 '락스': 31109,
 '코': 104392,
 '라고': 30704,
 '까고': 13462,
 '바비': 41281,
 '아이돌': 59650,
 '이라고': 83884,
 '깐': 13788,
 '안달': 60472,
 '난': 16007,
 '처럼': 102061,
 '보인다': 45735,
 '참 사람': 101538,
 '사람 들': 50028,
 '가 이기': 1943,
 '이기 면': 83334,
 '바비 가': 41282,
 '다그 냥': 22188,
 '안달 난': 60473,
 '난 것': 16010,
 '것 처럼': 6387,
 '처럼 보인다': 102079,
 '굿바이': 9961,
 '레닌': 31389,
 '표절': 107674,
 '인': 86029,
 '이해': 85895,
 '하는데': 109468,
 '왜': 72447,
 '뒤': 27812,
 '갈수록': 3435,
 '굿바이 레닌': 9962,
 '인 것': 86048,
 '것 은': 6353,
 '은 이해': 76746,
 '이해 하는데': 85940,
 '하는데 왜': 109481,
 '뒤 로': 27821,
 '로 갈수록': 31597,
 '갈수록 재미': 3456,
 '이건': 83061,
 '깨알': 13906,
 '캐스팅': 104122,
 '과': 8386,
 '질퍽': 100380,
 '하': 108355,
 '지': 98294,
 '않은': 61124,
 '산뜻한': 50585,
 '내': 16912,
 '용구성': 73342,
 '잘': 89474,
 '일드': 87070,
 '이건 정말': 83166,
 '캐스팅 과': 104123,
 '하 지': 108428,
 '지 않은': 98423,
 '내 용구성': 17031,
 '이 잘': 82544,
 '약탈': 62368,
 '를': 32552,
 '위': 74629,
 '변명': 43402,
 '이라': 83824,
 '저': 91824,
 '놈': 19428,
 '착한': 101437,
 '절대': 92953,
 '아닌': 58943,
 '걸': 5983,
 '요': 72887,
 '약탈 자': 62369,
 '자 를': 88620,
 '를 위': 33248,
 '위 한': 74645,
 '한 변명': 110550,
 '저 놈': 91840,
 '놈 들': 19431,
 '들 은': 28682,
 '은 착한': 76910,
 '착한 놈': 101439,
 '절대 아닌': 92970,
 '아닌 걸': 58948,
 '걸 요': 6081,
 '나름': 15199,
 '심오한': 57151,
 '뜻': 30544,
 '듯': 29070,
 '그냥': 10592,
 '학생': 110297,
 '선생': 52238,
 '놀아나는': 19419,
 '아님': 59056,
 '뜻 도': 30547,
 '도 있는': 25777,
 '있는 듯': 88026,
 '듯 그냥': 29084,
 '학생 이': 110303,
 '이 선생': 81816,
 '선생 과': 52239,
 '영화 는': 69614,
 '는 절대': 21067,
 '절대 아님': 92971,
 '보면서': 45281,
 '웃지': 74264,
 '않는': 60945,
 '건': 5784,
 '불가능하다': 48320,
 '않는 건': 60949,
 '재미없다': 90675,
 '지루하고': 98808,
 '같은': 4551,
 '음식': 78610,
 '인데': 86451,
 '만찬': 35628,
 '하고': 108529,
 '넘': 18363,
 '차이': 101384,
 '베트': 43337,
 '있고': 87889,
 '보는': 44456,
 '있는데': 88147,
 '게': 6418,
 '별로': 43562,
 '안': 60097,
 '나오고': 15431,
 '핀란드': 108211,
 '풍경': 107880,
 '이라도': 84002,
 '구': 9492,
 '경': 7080,
 '는데': 21293,
 '나옴': 15711,
 'ㅡㅡ': 800,
 '재미없다 지루하고': 90701,
 '음식 영화': 78615,
 '영화 인데': 70165,
 '인데 도': 86490,
 '의 만찬': 79127,
 '하고 넘': 108580,
 '은 이야기': 76742,
 '이야기 도': 85226,
 '도 있고': 25769,
 '보는 재미': 44517,
 '재미 도': 90475,
 '도 있는데': 25778,
 '있는데 이건': 88159,
 '볼 게': 46260,
 '게 없다': 6594,
 '도 별로': 25394,
 '별로 안': 43598,
 '안 나오고': 60119,
 '구 경': 9493,
 '그것 도': 10520,
 '안 나옴': 60143,
 '나옴 ㅡㅡ': 15716,
 '평범한': 107091,
 '수작': 54196,
 '는걸': 21277,
 '평범한 영화': 107097,
 '영화 가': 69437,
 '가 아닌': 1695,
 '수작 이라': 54209,
 '이라 는걸': 83834,
 '주제': 97275,
 '좋은데': 96578,
 '중반': 97983,
 '지루하다': 98875,
 '주제 는': 97277,
 '는 좋은데': 21112,
 '중반 부터': 97990,
 '부터 지루하다': 48016,
 '야': 62127,
 '그래서': 11061,
 '납득': 16675,
 '할': 111424,
 '수': 53899,
 '꼭': 14087,
 '꺼야': 13973,
 '납득 할': 16678,
 '할 수': 111477,
 '고추': 7930,
 '털어': 105572,
 '버려야': 42811,
 '할텐데': 111733,
 '카밀라': 103972,
 '벨': 43369,
 '발연기': 42080,
 '카밀라 벨': 103973,
 '센스': 53103,
 '연출': 68764,
 '력': 31533,
 '탁월한': 105233,
 '점': 93085,
 '센스 있는': 53107,
 '있는 연출': 88069,
 '연출 력': 68786,
 '그래서 점': 11080,
 '엄포스': 63879,
 '위력': 74678,
 '다시': 22502,
 '한번': 111155,
 '깨닫게': 13882,
 '해준': 112508,
 '꽃': 14216,
 '검사': 6212,
 '님': 21564,
 '좋았어요': 96423,
 '완전': 72145,
 '명품': 37940,
 '의 위력': 79838,
 '위력 을': 74679,
 '을 다시': 77337,
 '다시 한번': 22606,
 '한번 깨닫게': 111160,
 '깨닫게 해준': 13887,
 '검사 님': 6214,
 '님 도': 21582,
 '도 연기': 25683,
 '연기 정말': 68523,
 '정말 좋았어요': 94121,
 '명품 드라마': 37941,
 '졸': 95479,
 '쓰레기': 57799,
 '도안': 26191,
 '됌': 26935,
 'ㅋㅋ': 202,
 '아시': 59537,
 '간': 3263,
 '아까워': 58458,
 '도안 됌': 26196,
 '아시 간': 59538,
 '간 아까워': 3275,
 '재밌는데': 91274,
 '이리': 84701,
 '별 점': 43521,
 '점 이': 93197,
 '이 왜': 82335,
 '왜 이리': 72633,
 '라도': 30919,
 '기대했던': 12520,
 '죄인': 96712,
 '입니다': 87643,
 '기대했던 내': 12522,
 '내 가': 16913,
 '가 죄인': 2186,
 '아직도': 59851,
 '인생': 86674,
 '최고': 102879,
 '아직도 이': 59885,
 '는 내': 20401,
 '내 인생': 17048,
 '인생 의': 86695,
 '의 최고': 80174,
 '패션': 106588,
 '대한': 24158,
 '열정': 68948,
 '안나': 60429,
 '윈': 74787,
 '투어': 105896,
 '에 대한': 65268,
 '대한 열정': 24225,
 '키이라': 105040,
 '나이틀리': 15888,
 '하고자': 108873,
 '했던건': 112882,
 '대체': 24078,
 '일까': 87032,
 '틱장애': 106269,
 '키이라 나이틀리': 105041,
 '나이틀리 가': 15889,
 '가 연기': 1868,
 '허허': 113270,
 '원': 74316,
 '작가': 89140,
 '정신': 94301,
 '나간': 15017,
 '유령': 74880,
 '재미있겠네요': 90840,
 '작가 정신': 89172,
 '정신 나간': 94304,
 '있어': 88276,
 '보이는데': 45709,
 '관객': 8976,
 '명': 37765,
 '이네': 83543,
 '포스터 는': 107473,
 '는 있어': 21009,
 '관객 은': 8993,
 '은 명': 76306,
 '이렇게': 84458,
 '평가': 106998,
 '받는지': 41848,
 '모르겠다': 38241,
 '이 영화': 82271,
 '가 왜': 1902,
 '왜 이렇게': 72630,
 '이렇게 저': 84586,
 '저 평가': 91911,
 '받는지 모르겠다': 41849,
 '은은한': 77037,
 '매력': 36713,
 '은은한 매력': 77039,
 '매력 의': 36731,
 '의 영화': 79757,
 '알바생': 61414,
 '인가': 86273,
 '내용': 17265,
 '없고': 63930,
 '하나': 108978,
 '없음': 64686,
 '싱거운': 57255,
 'ㅇㅇ': 99,
 'ㅇ': 85,
 '시간': 55617,
 '낚임': 16006,
 '다 알바생': 21913,
 '알바생 인가': 61419,
 '내용 도': 17278,
 '도 없고': 25624,
 '하나 도': 109001,
 '도 없음': 25663,
 '없음 완전': 64715,
 '완전 별': 72202,
 '싱거운 영화': 57257,
 '영화 ㅇㅇ': 69414,
 '움 완전': 74005,
 '완전 낚임': 72174,
 '오게': 70951,
 '서리': 52027,
 '서리 한': 52029,
 '한 이': 110690,
 '맘': 36308,
 '들어요': 28948,
 '또': 30217,
 '보고싶은데': 44229,
 '방법': 42263,
 '없네': 64081,
 'ㅜㅡ': 646,
 '정말 맘': 93780,
 '맘 에': 36312,
 '에 들어요': 65323,
 '그래서 또': 11072,
 '또 보는': 30259,
 '방법 이': 42270,
 '이 없네': 82157,
 '윤제문': 75345,
 '이라는': 83938,
 '멋진': 37350,
 '배우': 42508,
 '발견': 42013,
 '하게': 108440,
 '됐어요': 26963,
 '소소한': 53371,
 '일': 86930,
 '탈': 105298,
 '잔잔한': 89419,
 '미소': 40521,
 '머금': 36969,
 '합니다': 111849,
 '음악': 78622,
 '조금': 95028,
 '아쉽네요': 59510,
 '주고': 96801,
 '싶은데': 57406,
 '올리고': 71557,
 '싶어': 57320,
 '줄게요': 97718,
 '멋진 배우': 37361,
 '배우 를': 42537,
 '를 발견': 32944,
 '발견 하게': 42016,
 '일 탈': 86992,
 '탈 이': 105301,
 '이 잔잔한': 82542,
 '잔잔한 미소': 89427,
 '미소 를': 40526,
 '를 머금': 32874,
 '머금 게': 36970,
 '음악 은': 78660,
 '은 조금': 76836,
 '조금 아쉽네요': 95048,
 '아쉽네요 ㅠㅠ': 59512,
 'ㅠㅠ 점': 747,
 '점 주고': 93245,
 '주고 싶은데': 96841,
 '싶은데 평점': 57411,
 '평점 올리고': 107276,
 '점 줄게요': 93272,
 '속지': 53631,
 '마시길': 34099,
 '낭비': 16739,
 '돈': 26396,
 '평점 에': 107267,
 '에 속지': 65700,
 '속지 마시길': 53634,
 '마시길 시간': 34100,
 '시간 낭비': 55641,
 '낭비 돈': 16745,
 '돈 낭비': 26400,
 '낭비 임': 16759,
 '리얼리티': 33722,
 '한데': 111114,
 '큰': 104847,
 '공감': 8099,
 '간다': 3299,
 '이민기': 84800,
 '캐릭터': 104078,
 '상': 50986,
 '분노조절': 48159,
 '장애': 90303,
 '초기': 102619,
 '증상': 98285,
 '일거다': 87009,
 '툭하면': 105930,
 '패': 106547,
 '물건': 39859,
 '오': 70908,
 '바': 41038,
 '였음': 69155,
 '초반': 102685,
 '엔': 67403,
 '신선했는데': 56637,
 '가면': 2646,
 '상태': 51244,
 '불가': 48307,
 '리얼리티 가': 33723,
 '큰 공감': 104853,
 '공감 은': 8125,
 '은 안': 76558,
 '안 간다': 60104,
 '캐릭터 는': 104083,
 '분노조절 장애': 48160,
 '사람 패': 50108,
 '패 고': 106548,
 '고 욕': 7511,
 '욕 하고': 73237,
 '하고 조금': 108804,
 '오 바': 70923,
 '바 였음': 41058,
 '극 초반': 11771,
 '초반 엔': 102701,
 '가면 갈수록': 2648,
 '정신 상태': 94314,
 '공감 불가': 8120,
 '마이너스': 34185,
 '없냐': 64077,
 'ㅋ': 129,
 '뮤비': 40287,
 '수준': 54223,
 '딱': 29517,
 '알': 61229,
 '하더군': 109592,
 'ㅉㅉ': 120,
 '북한': 48068,
 '이런거': 84401,
 '만들라고': 35248,
 '마이너스 는': 34187,
 '는 왜': 20941,
 '왜 없냐': 72590,
 '보고 영화': 44034,
 '영화 수준': 69929,
 '알 만': 61236,
 '북한 에서': 48072,
 '우리': 73516,
 '사랑': 50120,
 '우리 영화': 73556,
 '영화 를': 69713,
 '를 사랑': 33100,
 '사랑 합니다': 50205,
 '리스': 33686,
 '타르': 105148,
 '가르': 2617,
 '용의': 73408,
 '주인': 97172,
 '싶다': 57289,
 '누': 19652,
 '이랑': 84087,
 '근친상간': 11977,
 '이나': 83394,
 '소설': 53345,
 '속': 53552,
 '에선': 67278,
 '제일': 94793,
 '메': 37434,
 '라': 30573,
 '니스': 21527,
 '터': 105477,
 '였는데': 69042,
 '드래곤': 28187,
 '용이': 73412,
 '멋지': 37331,
 '웃음': 74236,
 '감독': 3542,
 '토르': 105708,
 '다크': 22831,
 '월드': 74545,
 '말': 36022,
 '기본': 12656,
 '선방': 52225,
 '했음': 112976,
 '데 너': 24915,
 '주인 이': 97175,
 '이 되고': 81223,
 '되고 싶다': 27019,
 '이나 하고': 83511,
 '소설 속': 53352,
 '속 에선': 53580,
 '놈 이': 19440,
 '자 이': 88631,
 '이 메': 81517,
 '라 니스': 30611,
 '니스 터': 21528,
 '드라마 속': 28048,
 '멋지 네': 37332,
 '네 웃음': 18718,
 '감독 님': 3561,
 '는 말': 20539,
 '말 아': 36060,
 '영혼': 69400,
 '어루만져': 62887,
 '수도': 54065,
 '있군요': 87949,
 '거친': 5765,
 '상사': 51100,
 '잠시': 89918,
 '잊고': 88537,
 '동화': 26882,
 '가 사람': 1545,
 '사람 의': 50065,
 '의 영혼': 79756,
 '영혼 을': 69405,
 '세 상사': 52852,
 '를 잠시': 33313,
 '잠시 잊고': 89922,
 '동화 같은': 26884,
 '같은 영화': 4631,
 '영화 에': 70020,
 '세르게이': 52957,
 '작은': 89199,
 '매운': 36803,
 '맛': 36330,
 '보여주마': 45596,
 '저그': 91925,
 '콩': 104617,
 '진호': 100266,
 '야 세르게이': 62167,
 '세르게이 작은': 52958,
 '작은 고추': 89200,
 '고추 의': 7931,
 '의 매운': 79146,
 '매운 맛': 36804,
 '맛 을': 36336,
 '을 보여주마': 77709,
 '저그 콩': 91927,
 '콩 진호': 104624,
 '진호 가': 100267,
 '가 간다': 915,
 '가슴': 2786,
 '시리': 55891,
 '있을까': 88456,
 '자체': 89026,
 '이렇게 가슴': 84459,
 '가슴 시리': 2812,
 '시리 게': 55892,
 '게 본': 6537,
 '본 드라마': 45981,
 '드라마 가': 27945,
 '가 또': 1315,
 '또 있을까': 30292,
 '감동 그': 3688,
 '그 자체': 10444,
 '난또': 16162,
 '꼬마': 14051,
 '애가': 61722,
 '무슨': 39401,
 '원한': 74516,
 '했더니': 112848,
 '혼자': 113859,
 '어쩌라고': 63308,
 '꼬마 애가': 14057,
 '애가 무슨': 61723,
 '했더니 그냥': 112849,
 '그냥 혼자': 10888,
 '재미있어요': 90940,
 '전': 92369,
 '좋아요': 96145,
 '충격': 103477,
 '기분': 12672,
 '완전히': 72320,
 '푹': 107781,
 '느낌': 20119,
 '활': 114397,
 '이라고는': 83922,
 '없는': 64112,
 '무거운': 39103,
 '지독하고': 98768,
 '차갑고': 101267,
 '그저': 11694,
 '일본인': 87196,
 '상상력': 51126,
 '대단한거': 23736,
 '같다는': 4455,
 '생각': 51472,
 '든다': 28346,
 '너무 충격': 18206,
 '기분 을': 12691,
 '을 완전히': 78025,
 '하는 느낌': 109201,
 '활 력': 114399,
 '도 없는': 25633,
 '일본인 들': 87197,
 '들 의': 28685,
 '의 상상력': 79401,
 '상상력 은': 51131,
 '은 정말': 76822,
 '정말 대단한거': 93746,
 '같다는 생각': 4458,
 '생각 이': 51522,
 '이 든다': 81295,
 '심심한': 57128,
 '심심한 영화': 57129,
 '언제': 63576,
 '나오나요': 15457,
 '언제 나오나요': 63588,
 '보는내내': 44602,
 '그대로': 10930,
 '들어맞는': 28925,
 '예측': 70863,
 '카리스마': 103929,
 '악역': 60057,
 '카리스마 없는': 103934,
 '불알': 48478,
 '나와서': 15731,
 '당황': 23475,
 '아무튼': 59377,
 '중간': 97876,
 '끝나는': 14572,
 '이 나와서': 80945,
 '아무튼 영화': 59378,
 '가 중간': 2202,
 '중간 에': 97889,
 '에 끝나는': 65119,
 '끝나는 느낌': 14575,
 '평범함': 107100,
 '녹아든': 19297,
 '일상': 87217,
 '평범함 속': 107101,
 '속 에': 53574,
 '에 녹아든': 65206,
 '평범한 일상': 107099,
 '계속': 7228,
 '보고있는데': 44265,
 '전개도': 92514,
 '느리고': 20207,
 '주인공': 97176,
 '은희': 77063,
 '한두': 111124,
 '컷': 104290,
 '나오면서': 15565,
 '소': 53161,
 '극적': 11847,
 '모습': 38386,
 '짜증': 100652,
 'ㅜㅜ': 610,
 '맨날': 36893,
 '끝나나': 14567,
 '대만': 23804,
 '있어요': 88332,
 '전개': 92454,
 '좀': 95588,
 '빨리': 49463,
 '전개도 느리고': 92516,
 '주인공 인': 97240,
 '극적 인': 11851,
 '인 모습': 86110,
 '모습 에': 38399,
 '에 짜증': 66177,
 '짜증 이': 100669,
 '이 ㅜㅜ': 80637,
 '언제 끝나나': 63583,
 '기 대만': 12219,
 '하고 있어요': 108776,
 '전개 좀': 92505,
 '좀 빨리': 95672,
 '빨리 빨리': 49485,
 '가슴속': 2846,
 '온': 71430,
 '감정': 3934,
 '예요': 70828,
 '사랑 하고': 50182,
 '감정 을': 3950,
 '영화 예요': 70091,
 '예요 정말': 70833,
 '정말 최고': 94163,
 '많은': 35812,
 '다큐': 22778,
 '우리나라': 73574,
 '슬픈': 55457,
 '현대': 113457,
 '사의': 50415,
 '단면': 22934,
 '대해': 24270,
 ...}

In [28]:
tfidf.inverse_transform(train_tfidf_df[0])

[array(['더빙', '더빙 진짜', '목소리', '아', '진짜', '진짜 짜증나네요', '짜증나네요'], dtype='<U30')]

In [29]:
from sklearn.linear_model import LogisticRegression

SA_lr = LogisticRegression(random_state = 0)

In [30]:
SA_lr.fit(train_tfidf_df, train_df['label'])

LogisticRegression(random_state=0)

In [32]:

#st = input('감성 분석할 문장입력 >> ')
st = "웃자 ^o^ 오늘은 좋은 날이 될 것 같은 예감100%! ^^*"

In [33]:

st2 = re.sub(r'[^ ㄱ-ㅎ|가-힣]+', "", st)
st2

'웃자  오늘은 좋은 날이 될 것 같은 예감 '

In [34]:

st_tfidf_df = tfidf.transform([st2])
st_tfidf_df

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16 stored elements and shape (1, 115612)>

In [35]:

st2_predict = SA_lr.predict(st_tfidf_df)

In [36]:

if(st2_predict== 0):
    print(st2 , "->> 부정 감성")
else :
    print(st2 , "->> 긍정 감성")

웃자  오늘은 좋은 날이 될 것 같은 예감  ->> 긍정 감성