In [1]:
import requests

header_data= {
    'accept': 'application/json',
    'Authorization': 'VXgWV/f5wELzapZjJF7FEqqtFhPbNA8KBIWia3SXOCvY+CXEUok1DhybfbP4USE/g2b/QYT62C2mw3zcSWj2pg==',
}

param_data = (
    ('page', '1'),
    ('perPage', '1000'),
    ('serviceKey', 'VXgWV/f5wELzapZjJF7FEqqtFhPbNA8KBIWia3SXOCvY+CXEUok1DhybfbP4USE/g2b/QYT62C2mw3zcSWj2pg=='),
)

url = 'https://api.odcloud.kr/api/15069309/v1/uddi:973ad0df-617a-4565-8e82-8ea7869e75d4'
## decode key가 적용되었음.
## api마다 연결이 되지 않는다고 한다면, encode, decode를 바꾸어 테스트해볼 것.
response = requests.get(url, headers=header_data, params=param_data)
response

In [2]:
json_data = response.json()
#json_data

In [3]:
import pickle

In [4]:
with open('covid-gokr.json', 'wb') as fp:
    pickle.dump(json_data, fp)

In [5]:
# fp = file.open('covid-gokr.json', 'wb')
# fp.close()

In [6]:
with open('covid-gokr.json', 'rb') as fp:
    json_read_data = pickle.load(fp)

In [7]:
type(json_read_data)

dict

In [8]:
#json_read_data

In [9]:
#json_data

In [10]:
json_data['currentCount']

1000

In [11]:
json_data['data'][:5]

[{'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '당직자공용 기자',
  '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '헤럴드경제',
  '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
  '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '신종코,추가,환자,확진'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '이상규',
  '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '매일경제',
  '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
  '일자': '2020-02-01',
  '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001',
  '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '접촉자,신종코,감시,확진,검사,속보'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '황재희',
  '본문': '[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang',
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '아주경제',
  '원본주소': 'http://www.ajunews.com/view/20200201134957462',
  '일자': '2020-02-01',
  '제목': '[속보] 신종 코로나 확진자 12명…70명 검사 중',
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001',
  '키워드': '신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검사,사람,70명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '확진자,코로나바이러스,코로,검사,신종,확인,사람'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '이미경(capital);',
  '본문': "[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '한국경제',
  '원본주소': 'https://www.hankyung.com/society/article/2020020121817',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002',
  '키워드': '신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '확진환자,1명,6명,신종코,추가,환자,확진,속보,하루'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '김봄이',
  '본문': "'신종코로나' 확진환자 1명 추가…국내 총 12명",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '매일신문',
  '원본주소': 'https://news.imaeil.com/Society/2020020109431879372',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001',
  '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '신종코,추가,환자,확진'}]

In [12]:
data_values = json_data.get('data')
data_values[:2]

[{'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '당직자공용 기자',
  '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '헤럴드경제',
  '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
  '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '신종코,추가,환자,확진'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '이상규',
  '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '매일경제',
  '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
  '일자': '2020-02-01',
  '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001',
  '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '접촉자,신종코,감시,확진,검사,속보'}]

In [13]:
type(data_values)

list

In [14]:
print('신문기사수>> ', len(data_values))

신문기사수>>  1000

In [15]:
data_values[0]

{'개체명(기업기관)': None,
 '개체명(인물)': None,
 '개체명(지역)': None,
 '기고자': '당직자공용 기자',
 '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
 '사건_사고 분류1': None,
 '사건_사고 분류2': None,
 '사건_사고 분류3': None,
 '언론사': '헤럴드경제',
 '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
 '일자': '2020-02-01',
 '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
 '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
 '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
 '통합 분류1': '사회>의료_건강',
 '통합 분류2': None,
 '통합 분류3': None,
 '특성추출': '신종코,추가,환자,확진'}

In [16]:
com = data_values[0]['언론사']
com

'헤럴드경제'

In [17]:
content = data_values[0]['본문']
content

"[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews"

In [18]:
addr = data_values[0]['원본주소']
addr

'http://biz.heraldcorp.com/view.php?ud=20200201000027'

In [19]:
title = data_values[0]['제목']
title

"[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어"

In [20]:
date = data_values[0]['일자']
date

'2020-02-01'

In [21]:
field = data_values[0]['통합 분류1']
field

'사회>의료_건강'

In [22]:
one_row = []
one_row.append(title)
one_row.append(content)
one_row.append(field)
one_row.append(date)
one_row.append(addr)
one_row.append(com)
one_row

["[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
 "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
 '사회>의료_건강',
 '2020-02-01',
 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
 '헤럴드경제']

In [23]:
total_row = []
for no in range(1000):
    com = data_values[no]['언론사']
    content = data_values[no]['본문']
    addr = data_values[no]['원본주소']
    date = data_values[no]['일자']
    field = data_values[no]['통합 분류1']
    title = data_values[no]['제목']
    one_row = []
    one_row.append(title)
    one_row.append(content)
    one_row.append(field)
    one_row.append(date)
    one_row.append(addr)
    one_row.append(com)
    #print(one_row)
    total_row.append(one_row)
    print('전체기사수 >> ', len(total_row))

전체기사수 >>  1
전체기사수 >>  2
전체기사수 >>  3
전체기사수 >>  4
전체기사수 >>  5
전체기사수 >>  6
전체기사수 >>  7
전체기사수 >>  8
전체기사수 >>  9
전체기사수 >>  10
전체기사수 >>  11
전체기사수 >>  12
전체기사수 >>  13
전체기사수 >>  14
전체기사수 >>  15
전체기사수 >>  16
전체기사수 >>  17
전체기사수 >>  18
전체기사수 >>  19
전체기사수 >>  20
전체기사수 >>  21
전체기사수 >>  22
전체기사수 >>  23
전체기사수 >>  24
전체기사수 >>  25
전체기사수 >>  26
전체기사수 >>  27
전체기사수 >>  28
전체기사수 >>  29
전체기사수 >>  30
전체기사수 >>  31
전체기사수 >>  32
전체기사수 >>  33
전체기사수 >>  34
전체기사수 >>  35
전체기사수 >>  36
전체기사수 >>  37
전체기사수 >>  38
전체기사수 >>  39
전체기사수 >>  40
전체기사수 >>  41
전체기사수 >>  42
전체기사수 >>  43
전체기사수 >>  44
전체기사수 >>  45
전체기사수 >>  46
전체기사수 >>  47
전체기사수 >>  48
전체기사수 >>  49
전체기사수 >>  50
전체기사수 >>  51
전체기사수 >>  52
전체기사수 >>  53
전체기사수 >>  54
전체기사수 >>  55
전체기사수 >>  56
전체기사수 >>  57
전체기사수 >>  58
전체기사수 >>  59
전체기사수 >>  60
전체기사수 >>  61
전체기사수 >>  62
전체기사수 >>  63
전체기사수 >>  64
전체기사수 >>  65
전체기사수 >>  66
전체기사수 >>  67
전체기사수 >>  68
전체기사수 >>  69
전체기사수 >>  70
전체기사수 >>  71
전체기사수 >>  72
전체기사수 >>  73
전체기사수 >>  74
전체기사수 >>  75
전체기사수 >>  76
전체기사수 >>  77
전체기사수 >>  78
전체기사수 >>  79
전체기사수 >>  80
전체기사수 >>  81
전체기사수 >>  82
전체기사수 >>  83
전체기사수 >>  84
전체기사수 >>  85
전체기사수 >>  86
전체기사수 >>  87
전체기사수 >>  88
전체기사수 >>  89
전체기사수 >>  90
전체기사수 >>  91
전체기사수 >>  92
전체기사수 >>  93
전체기사수 >>  94
전체기사수 >>  95
전체기사수 >>  96
전체기사수 >>  97
전체기사수 >>  98
전체기사수 >>  99
전체기사수 >>  100
전체기사수 >>  101
전체기사수 >>  102
전체기사수 >>  103
전체기사수 >>  104
전체기사수 >>  105
전체기사수 >>  106
전체기사수 >>  107
전체기사수 >>  108
전체기사수 >>  109
전체기사수 >>  110
전체기사수 >>  111
전체기사수 >>  112
전체기사수 >>  113
전체기사수 >>  114
전체기사수 >>  115
전체기사수 >>  116
전체기사수 >>  117
전체기사수 >>  118
전체기사수 >>  119
전체기사수 >>  120
전체기사수 >>  121
전체기사수 >>  122
전체기사수 >>  123
전체기사수 >>  124
전체기사수 >>  125
전체기사수 >>  126
전체기사수 >>  127
전체기사수 >>  128
전체기사수 >>  129
전체기사수 >>  130
전체기사수 >>  131
전체기사수 >>  132
전체기사수 >>  133
전체기사수 >>  134
전체기사수 >>  135
전체기사수 >>  136
전체기사수 >>  137
전체기사수 >>  138
전체기사수 >>  139
전체기사수 >>  140
전체기사수 >>  141
전체기사수 >>  142
전체기사수 >>  143
전체기사수 >>  144
전체기사수 >>  145
전체기사수 >>  146
전체기사수 >>  147
전체기사수 >>  148
전체기사수 >>  149
전체기사수 >>  150
전체기사수 >>  151
전체기사수 >>  152
전체기사수 >>  153
전체기사수 >>  154
전체기사수 >>  155
전체기사수 >>  156
전체기사수 >>  157
전체기사수 >>  158
전체기사수 >>  159
전체기사수 >>  160
전체기사수 >>  161
전체기사수 >>  162
전체기사수 >>  163
전체기사수 >>  164
전체기사수 >>  165
전체기사수 >>  166
전체기사수 >>  167
전체기사수 >>  168
전체기사수 >>  169
전체기사수 >>  170
전체기사수 >>  171
전체기사수 >>  172
전체기사수 >>  173
전체기사수 >>  174
전체기사수 >>  175
전체기사수 >>  176
전체기사수 >>  177
전체기사수 >>  178
전체기사수 >>  179
전체기사수 >>  180
전체기사수 >>  181
전체기사수 >>  182
전체기사수 >>  183
전체기사수 >>  184
전체기사수 >>  185
전체기사수 >>  186
전체기사수 >>  187
전체기사수 >>  188
전체기사수 >>  189
전체기사수 >>  190
전체기사수 >>  191
전체기사수 >>  192
전체기사수 >>  193
전체기사수 >>  194
전체기사수 >>  195
전체기사수 >>  196
전체기사수 >>  197
전체기사수 >>  198
전체기사수 >>  199
전체기사수 >>  200
전체기사수 >>  201
전체기사수 >>  202
전체기사수 >>  203
전체기사수 >>  204
전체기사수 >>  205
전체기사수 >>  206
전체기사수 >>  207
전체기사수 >>  208
전체기사수 >>  209
전체기사수 >>  210
전체기사수 >>  211
전체기사수 >>  212
전체기사수 >>  213
전체기사수 >>  214
전체기사수 >>  215
전체기사수 >>  216
전체기사수 >>  217
전체기사수 >>  218
전체기사수 >>  219
전체기사수 >>  220
전체기사수 >>  221
전체기사수 >>  222
전체기사수 >>  223
전체기사수 >>  224
전체기사수 >>  225
전체기사수 >>  226
전체기사수 >>  227
전체기사수 >>  228
전체기사수 >>  229
전체기사수 >>  230
전체기사수 >>  231
전체기사수 >>  232
전체기사수 >>  233
전체기사수 >>  234
전체기사수 >>  235
전체기사수 >>  236
전체기사수 >>  237
전체기사수 >>  238
전체기사수 >>  239
전체기사수 >>  240
전체기사수 >>  241
전체기사수 >>  242
전체기사수 >>  243
전체기사수 >>  244
전체기사수 >>  245
전체기사수 >>  246
전체기사수 >>  247
전체기사수 >>  248
전체기사수 >>  249
전체기사수 >>  250
전체기사수 >>  251
전체기사수 >>  252
전체기사수 >>  253
전체기사수 >>  254
전체기사수 >>  255
전체기사수 >>  256
전체기사수 >>  257
전체기사수 >>  258
전체기사수 >>  259
전체기사수 >>  260
전체기사수 >>  261
전체기사수 >>  262
전체기사수 >>  263
전체기사수 >>  264
전체기사수 >>  265
전체기사수 >>  266
전체기사수 >>  267
전체기사수 >>  268
전체기사수 >>  269
전체기사수 >>  270
전체기사수 >>  271
전체기사수 >>  272
전체기사수 >>  273
전체기사수 >>  274
전체기사수 >>  275
전체기사수 >>  276
전체기사수 >>  277
전체기사수 >>  278
전체기사수 >>  279
전체기사수 >>  280
전체기사수 >>  281
전체기사수 >>  282
전체기사수 >>  283
전체기사수 >>  284
전체기사수 >>  285
전체기사수 >>  286
전체기사수 >>  287
전체기사수 >>  288
전체기사수 >>  289
전체기사수 >>  290
전체기사수 >>  291
전체기사수 >>  292
전체기사수 >>  293
전체기사수 >>  294
전체기사수 >>  295
전체기사수 >>  296
전체기사수 >>  297
전체기사수 >>  298
전체기사수 >>  299
전체기사수 >>  300
전체기사수 >>  301
전체기사수 >>  302
전체기사수 >>  303
전체기사수 >>  304
전체기사수 >>  305
전체기사수 >>  306
전체기사수 >>  307
전체기사수 >>  308
전체기사수 >>  309
전체기사수 >>  310
전체기사수 >>  311
전체기사수 >>  312
전체기사수 >>  313
전체기사수 >>  314
전체기사수 >>  315
전체기사수 >>  316
전체기사수 >>  317
전체기사수 >>  318
전체기사수 >>  319
전체기사수 >>  320
전체기사수 >>  321
전체기사수 >>  322
전체기사수 >>  323
전체기사수 >>  324
전체기사수 >>  325
전체기사수 >>  326
전체기사수 >>  327
전체기사수 >>  328
전체기사수 >>  329
전체기사수 >>  330
전체기사수 >>  331
전체기사수 >>  332
전체기사수 >>  333
전체기사수 >>  334
전체기사수 >>  335
전체기사수 >>  336
전체기사수 >>  337
전체기사수 >>  338
전체기사수 >>  339
전체기사수 >>  340
전체기사수 >>  341
전체기사수 >>  342
전체기사수 >>  343
전체기사수 >>  344
전체기사수 >>  345
전체기사수 >>  346
전체기사수 >>  347
전체기사수 >>  348
전체기사수 >>  349
전체기사수 >>  350
전체기사수 >>  351
전체기사수 >>  352
전체기사수 >>  353
전체기사수 >>  354
전체기사수 >>  355
전체기사수 >>  356
전체기사수 >>  357
전체기사수 >>  358
전체기사수 >>  359
전체기사수 >>  360
전체기사수 >>  361
전체기사수 >>  362
전체기사수 >>  363
전체기사수 >>  364
전체기사수 >>  365
전체기사수 >>  366
전체기사수 >>  367
전체기사수 >>  368
전체기사수 >>  369
전체기사수 >>  370
전체기사수 >>  371
전체기사수 >>  372
전체기사수 >>  373
전체기사수 >>  374
전체기사수 >>  375
전체기사수 >>  376
전체기사수 >>  377
전체기사수 >>  378
전체기사수 >>  379
전체기사수 >>  380
전체기사수 >>  381
전체기사수 >>  382
전체기사수 >>  383
전체기사수 >>  384
전체기사수 >>  385
전체기사수 >>  386
전체기사수 >>  387
전체기사수 >>  388
전체기사수 >>  389
전체기사수 >>  390
전체기사수 >>  391
전체기사수 >>  392
전체기사수 >>  393
전체기사수 >>  394
전체기사수 >>  395
전체기사수 >>  396
전체기사수 >>  397
전체기사수 >>  398
전체기사수 >>  399
전체기사수 >>  400
전체기사수 >>  401
전체기사수 >>  402
전체기사수 >>  403
전체기사수 >>  404
전체기사수 >>  405
전체기사수 >>  406
전체기사수 >>  407
전체기사수 >>  408
전체기사수 >>  409
전체기사수 >>  410
전체기사수 >>  411
전체기사수 >>  412
전체기사수 >>  413
전체기사수 >>  414
전체기사수 >>  415
전체기사수 >>  416
전체기사수 >>  417
전체기사수 >>  418
전체기사수 >>  419
전체기사수 >>  420
전체기사수 >>  421
전체기사수 >>  422
전체기사수 >>  423
전체기사수 >>  424
전체기사수 >>  425
전체기사수 >>  426
전체기사수 >>  427
전체기사수 >>  428
전체기사수 >>  429
전체기사수 >>  430
전체기사수 >>  431
전체기사수 >>  432
전체기사수 >>  433
전체기사수 >>  434
전체기사수 >>  435
전체기사수 >>  436
전체기사수 >>  437
전체기사수 >>  438
전체기사수 >>  439
전체기사수 >>  440
전체기사수 >>  441
전체기사수 >>  442
전체기사수 >>  443
전체기사수 >>  444
전체기사수 >>  445
전체기사수 >>  446
전체기사수 >>  447
전체기사수 >>  448
전체기사수 >>  449
전체기사수 >>  450
전체기사수 >>  451
전체기사수 >>  452
전체기사수 >>  453
전체기사수 >>  454
전체기사수 >>  455
전체기사수 >>  456
전체기사수 >>  457
전체기사수 >>  458
전체기사수 >>  459
전체기사수 >>  460
전체기사수 >>  461
전체기사수 >>  462
전체기사수 >>  463
전체기사수 >>  464
전체기사수 >>  465
전체기사수 >>  466
전체기사수 >>  467
전체기사수 >>  468
전체기사수 >>  469
전체기사수 >>  470
전체기사수 >>  471
전체기사수 >>  472
전체기사수 >>  473
전체기사수 >>  474
전체기사수 >>  475
전체기사수 >>  476
전체기사수 >>  477
전체기사수 >>  478
전체기사수 >>  479
전체기사수 >>  480
전체기사수 >>  481
전체기사수 >>  482
전체기사수 >>  483
전체기사수 >>  484
전체기사수 >>  485
전체기사수 >>  486
전체기사수 >>  487
전체기사수 >>  488
전체기사수 >>  489
전체기사수 >>  490
전체기사수 >>  491
전체기사수 >>  492
전체기사수 >>  493
전체기사수 >>  494
전체기사수 >>  495
전체기사수 >>  496
전체기사수 >>  497
전체기사수 >>  498
전체기사수 >>  499
전체기사수 >>  500
전체기사수 >>  501
전체기사수 >>  502
전체기사수 >>  503
전체기사수 >>  504
전체기사수 >>  505
전체기사수 >>  506
전체기사수 >>  507
전체기사수 >>  508
전체기사수 >>  509
전체기사수 >>  510
전체기사수 >>  511
전체기사수 >>  512
전체기사수 >>  513
전체기사수 >>  514
전체기사수 >>  515
전체기사수 >>  516
전체기사수 >>  517
전체기사수 >>  518
전체기사수 >>  519
전체기사수 >>  520
전체기사수 >>  521
전체기사수 >>  522
전체기사수 >>  523
전체기사수 >>  524
전체기사수 >>  525
전체기사수 >>  526
전체기사수 >>  527
전체기사수 >>  528
전체기사수 >>  529
전체기사수 >>  530
전체기사수 >>  531
전체기사수 >>  532
전체기사수 >>  533
전체기사수 >>  534
전체기사수 >>  535
전체기사수 >>  536
전체기사수 >>  537
전체기사수 >>  538
전체기사수 >>  539
전체기사수 >>  540
전체기사수 >>  541
전체기사수 >>  542
전체기사수 >>  543
전체기사수 >>  544
전체기사수 >>  545
전체기사수 >>  546
전체기사수 >>  547
전체기사수 >>  548
전체기사수 >>  549
전체기사수 >>  550
전체기사수 >>  551
전체기사수 >>  552
전체기사수 >>  553
전체기사수 >>  554
전체기사수 >>  555
전체기사수 >>  556
전체기사수 >>  557
전체기사수 >>  558
전체기사수 >>  559
전체기사수 >>  560
전체기사수 >>  561
전체기사수 >>  562
전체기사수 >>  563
전체기사수 >>  564
전체기사수 >>  565
전체기사수 >>  566
전체기사수 >>  567
전체기사수 >>  568
전체기사수 >>  569
전체기사수 >>  570
전체기사수 >>  571
전체기사수 >>  572
전체기사수 >>  573
전체기사수 >>  574
전체기사수 >>  575
전체기사수 >>  576
전체기사수 >>  577
전체기사수 >>  578
전체기사수 >>  579
전체기사수 >>  580
전체기사수 >>  581
전체기사수 >>  582
전체기사수 >>  583
전체기사수 >>  584
전체기사수 >>  585
전체기사수 >>  586
전체기사수 >>  587
전체기사수 >>  588
전체기사수 >>  589
전체기사수 >>  590
전체기사수 >>  591
전체기사수 >>  592
전체기사수 >>  593
전체기사수 >>  594
전체기사수 >>  595
전체기사수 >>  596
전체기사수 >>  597
전체기사수 >>  598
전체기사수 >>  599
전체기사수 >>  600
전체기사수 >>  601
전체기사수 >>  602
전체기사수 >>  603
전체기사수 >>  604
전체기사수 >>  605
전체기사수 >>  606
전체기사수 >>  607
전체기사수 >>  608
전체기사수 >>  609
전체기사수 >>  610
전체기사수 >>  611
전체기사수 >>  612
전체기사수 >>  613
전체기사수 >>  614
전체기사수 >>  615
전체기사수 >>  616
전체기사수 >>  617
전체기사수 >>  618
전체기사수 >>  619
전체기사수 >>  620
전체기사수 >>  621
전체기사수 >>  622
전체기사수 >>  623
전체기사수 >>  624
전체기사수 >>  625
전체기사수 >>  626
전체기사수 >>  627
전체기사수 >>  628
전체기사수 >>  629
전체기사수 >>  630
전체기사수 >>  631
전체기사수 >>  632
전체기사수 >>  633
전체기사수 >>  634
전체기사수 >>  635
전체기사수 >>  636
전체기사수 >>  637
전체기사수 >>  638
전체기사수 >>  639
전체기사수 >>  640
전체기사수 >>  641
전체기사수 >>  642
전체기사수 >>  643
전체기사수 >>  644
전체기사수 >>  645
전체기사수 >>  646
전체기사수 >>  647
전체기사수 >>  648
전체기사수 >>  649
전체기사수 >>  650
전체기사수 >>  651
전체기사수 >>  652
전체기사수 >>  653
전체기사수 >>  654
전체기사수 >>  655
전체기사수 >>  656
전체기사수 >>  657
전체기사수 >>  658
전체기사수 >>  659
전체기사수 >>  660
전체기사수 >>  661
전체기사수 >>  662
전체기사수 >>  663
전체기사수 >>  664
전체기사수 >>  665
전체기사수 >>  666
전체기사수 >>  667
전체기사수 >>  668
전체기사수 >>  669
전체기사수 >>  670
전체기사수 >>  671
전체기사수 >>  672
전체기사수 >>  673
전체기사수 >>  674
전체기사수 >>  675
전체기사수 >>  676
전체기사수 >>  677
전체기사수 >>  678
전체기사수 >>  679
전체기사수 >>  680
전체기사수 >>  681
전체기사수 >>  682
전체기사수 >>  683
전체기사수 >>  684
전체기사수 >>  685
전체기사수 >>  686
전체기사수 >>  687
전체기사수 >>  688
전체기사수 >>  689
전체기사수 >>  690
전체기사수 >>  691
전체기사수 >>  692
전체기사수 >>  693
전체기사수 >>  694
전체기사수 >>  695
전체기사수 >>  696
전체기사수 >>  697
전체기사수 >>  698
전체기사수 >>  699
전체기사수 >>  700
전체기사수 >>  701
전체기사수 >>  702
전체기사수 >>  703
전체기사수 >>  704
전체기사수 >>  705
전체기사수 >>  706
전체기사수 >>  707
전체기사수 >>  708
전체기사수 >>  709
전체기사수 >>  710
전체기사수 >>  711
전체기사수 >>  712
전체기사수 >>  713
전체기사수 >>  714
전체기사수 >>  715
전체기사수 >>  716
전체기사수 >>  717
전체기사수 >>  718
전체기사수 >>  719
전체기사수 >>  720
전체기사수 >>  721
전체기사수 >>  722
전체기사수 >>  723
전체기사수 >>  724
전체기사수 >>  725
전체기사수 >>  726
전체기사수 >>  727
전체기사수 >>  728
전체기사수 >>  729
전체기사수 >>  730
전체기사수 >>  731
전체기사수 >>  732
전체기사수 >>  733
전체기사수 >>  734
전체기사수 >>  735
전체기사수 >>  736
전체기사수 >>  737
전체기사수 >>  738
전체기사수 >>  739
전체기사수 >>  740
전체기사수 >>  741
전체기사수 >>  742
전체기사수 >>  743
전체기사수 >>  744
전체기사수 >>  745
전체기사수 >>  746
전체기사수 >>  747
전체기사수 >>  748
전체기사수 >>  749
전체기사수 >>  750
전체기사수 >>  751
전체기사수 >>  752
전체기사수 >>  753
전체기사수 >>  754
전체기사수 >>  755
전체기사수 >>  756
전체기사수 >>  757
전체기사수 >>  758
전체기사수 >>  759
전체기사수 >>  760
전체기사수 >>  761
전체기사수 >>  762
전체기사수 >>  763
전체기사수 >>  764
전체기사수 >>  765
전체기사수 >>  766
전체기사수 >>  767
전체기사수 >>  768
전체기사수 >>  769
전체기사수 >>  770
전체기사수 >>  771
전체기사수 >>  772
전체기사수 >>  773
전체기사수 >>  774
전체기사수 >>  775
전체기사수 >>  776
전체기사수 >>  777
전체기사수 >>  778
전체기사수 >>  779
전체기사수 >>  780
전체기사수 >>  781
전체기사수 >>  782
전체기사수 >>  783
전체기사수 >>  784
전체기사수 >>  785
전체기사수 >>  786
전체기사수 >>  787
전체기사수 >>  788
전체기사수 >>  789
전체기사수 >>  790
전체기사수 >>  791
전체기사수 >>  792
전체기사수 >>  793
전체기사수 >>  794
전체기사수 >>  795
전체기사수 >>  796
전체기사수 >>  797
전체기사수 >>  798
전체기사수 >>  799
전체기사수 >>  800
전체기사수 >>  801
전체기사수 >>  802
전체기사수 >>  803
전체기사수 >>  804
전체기사수 >>  805
전체기사수 >>  806
전체기사수 >>  807
전체기사수 >>  808
전체기사수 >>  809
전체기사수 >>  810
전체기사수 >>  811
전체기사수 >>  812
전체기사수 >>  813
전체기사수 >>  814
전체기사수 >>  815
전체기사수 >>  816
전체기사수 >>  817
전체기사수 >>  818
전체기사수 >>  819
전체기사수 >>  820
전체기사수 >>  821
전체기사수 >>  822
전체기사수 >>  823
전체기사수 >>  824
전체기사수 >>  825
전체기사수 >>  826
전체기사수 >>  827
전체기사수 >>  828
전체기사수 >>  829
전체기사수 >>  830
전체기사수 >>  831
전체기사수 >>  832
전체기사수 >>  833
전체기사수 >>  834
전체기사수 >>  835
전체기사수 >>  836
전체기사수 >>  837
전체기사수 >>  838
전체기사수 >>  839
전체기사수 >>  840
전체기사수 >>  841
전체기사수 >>  842
전체기사수 >>  843
전체기사수 >>  844
전체기사수 >>  845
전체기사수 >>  846
전체기사수 >>  847
전체기사수 >>  848
전체기사수 >>  849
전체기사수 >>  850
전체기사수 >>  851
전체기사수 >>  852
전체기사수 >>  853
전체기사수 >>  854
전체기사수 >>  855
전체기사수 >>  856
전체기사수 >>  857
전체기사수 >>  858
전체기사수 >>  859
전체기사수 >>  860
전체기사수 >>  861
전체기사수 >>  862
전체기사수 >>  863
전체기사수 >>  864
전체기사수 >>  865
전체기사수 >>  866
전체기사수 >>  867
전체기사수 >>  868
전체기사수 >>  869
전체기사수 >>  870
전체기사수 >>  871
전체기사수 >>  872
전체기사수 >>  873
전체기사수 >>  874
전체기사수 >>  875
전체기사수 >>  876
전체기사수 >>  877
전체기사수 >>  878
전체기사수 >>  879
전체기사수 >>  880
전체기사수 >>  881
전체기사수 >>  882
전체기사수 >>  883
전체기사수 >>  884
전체기사수 >>  885
전체기사수 >>  886
전체기사수 >>  887
전체기사수 >>  888
전체기사수 >>  889
전체기사수 >>  890
전체기사수 >>  891
전체기사수 >>  892
전체기사수 >>  893
전체기사수 >>  894
전체기사수 >>  895
전체기사수 >>  896
전체기사수 >>  897
전체기사수 >>  898
전체기사수 >>  899
전체기사수 >>  900
전체기사수 >>  901
전체기사수 >>  902
전체기사수 >>  903
전체기사수 >>  904
전체기사수 >>  905
전체기사수 >>  906
전체기사수 >>  907
전체기사수 >>  908
전체기사수 >>  909
전체기사수 >>  910
전체기사수 >>  911
전체기사수 >>  912
전체기사수 >>  913
전체기사수 >>  914
전체기사수 >>  915
전체기사수 >>  916
전체기사수 >>  917
전체기사수 >>  918
전체기사수 >>  919
전체기사수 >>  920
전체기사수 >>  921
전체기사수 >>  922
전체기사수 >>  923
전체기사수 >>  924
전체기사수 >>  925
전체기사수 >>  926
전체기사수 >>  927
전체기사수 >>  928
전체기사수 >>  929
전체기사수 >>  930
전체기사수 >>  931
전체기사수 >>  932
전체기사수 >>  933
전체기사수 >>  934
전체기사수 >>  935
전체기사수 >>  936
전체기사수 >>  937
전체기사수 >>  938
전체기사수 >>  939
전체기사수 >>  940
전체기사수 >>  941
전체기사수 >>  942
전체기사수 >>  943
전체기사수 >>  944
전체기사수 >>  945
전체기사수 >>  946
전체기사수 >>  947
전체기사수 >>  948
전체기사수 >>  949
전체기사수 >>  950
전체기사수 >>  951
전체기사수 >>  952
전체기사수 >>  953
전체기사수 >>  954
전체기사수 >>  955
전체기사수 >>  956
전체기사수 >>  957
전체기사수 >>  958
전체기사수 >>  959
전체기사수 >>  960
전체기사수 >>  961
전체기사수 >>  962
전체기사수 >>  963
전체기사수 >>  964
전체기사수 >>  965
전체기사수 >>  966
전체기사수 >>  967
전체기사수 >>  968
전체기사수 >>  969
전체기사수 >>  970
전체기사수 >>  971
전체기사수 >>  972
전체기사수 >>  973
전체기사수 >>  974
전체기사수 >>  975
전체기사수 >>  976
전체기사수 >>  977
전체기사수 >>  978
전체기사수 >>  979
전체기사수 >>  980
전체기사수 >>  981
전체기사수 >>  982
전체기사수 >>  983
전체기사수 >>  984
전체기사수 >>  985
전체기사수 >>  986
전체기사수 >>  987
전체기사수 >>  988
전체기사수 >>  989
전체기사수 >>  990
전체기사수 >>  991
전체기사수 >>  992
전체기사수 >>  993
전체기사수 >>  994
전체기사수 >>  995
전체기사수 >>  996
전체기사수 >>  997
전체기사수 >>  998
전체기사수 >>  999
전체기사수 >>  1000

In [24]:
with open('covid-sub-data.json', 'wb') as fp:
    pickle.dump(total_row, fp)

In [25]:
with open('covid-sub-data.json', 'rb') as fp:
    json_sub_data = pickle.load(fp)
json_sub_data[:2]

[["[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
  "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
  '사회>의료_건강',
  '2020-02-01',
  'http://biz.heraldcorp.com/view.php?ud=20200201000027',
  '헤럴드경제'],
 ['[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
  '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
  '사회>의료_건강',
  '2020-02-01',
  'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
  '매일경제']]

In [26]:
import pandas as pd
import numpy as np

In [27]:
with open('covid-sub-data-dic.json', 'wb') as fp:
    pickle.dump(data_values, fp)

In [28]:
with open('covid-sub-data-dic.json', 'rb') as fp:
    json_sub_data_dic = pickle.load(fp)
#json_sub_data_dic

In [29]:
df_test = pd.DataFrame(json_sub_data_dic) #[dic, dic, dic]
df_test[:2]

,개체명(기업기관),개체명(인물),개체명(지역),기고자,본문,사건_사고 분류1,사건_사고 분류2,사건_사고 분류3,언론사,원본주소,일자,제목,주소,키워드,통합 분류1,통합 분류2,통합 분류3,특성추출
0,None,None,None,당직자공용 기자,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,None,None,None,헤럴드경제,http://biz.heraldcorp.com/view.php?ud=20200201...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명",사회>의료_건강,None,None,"신종코,추가,환자,확진"
1,None,None,None,이상규,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,None,None,None,매일경제,http://news.mk.co.kr/newsRead.php?no=104142&ye...,2020-02-01,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시",사회>의료_건강,None,None,"접촉자,신종코,감시,확진,검사,속보"

In [30]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   개체명(기업기관)  574 non-null    object
 1   개체명(인물)    0 non-null      object
 2   개체명(지역)    0 non-null      object
 3   기고자        939 non-null    object
 4   본문         1000 non-null   object
 5   사건_사고 분류1  0 non-null      object
 6   사건_사고 분류2  0 non-null      object
 7   사건_사고 분류3  0 non-null      object
 8   언론사        1000 non-null   object
 9   원본주소       955 non-null    object
 10  일자         1000 non-null   object
 11  제목         1000 non-null   object
 12  주소         1000 non-null   object
 13  키워드        1000 non-null   object
 14  통합 분류1     791 non-null    object
 15  통합 분류2     0 non-null      object
 16  통합 분류3     0 non-null      object
 17  특성추출       1000 non-null   object
dtypes: object(18)
memory usage: 140.8+ KB

In [31]:
df_test.shape

(1000, 18)

In [32]:
df_test.columns

Index(['개체명(기업기관)', '개체명(인물)', '개체명(지역)', '기고자', '본문', '사건_사고 분류1',
       '사건_사고 분류2', '사건_사고 분류3', '언론사', '원본주소', '일자', '제목', '주소', '키워드',
       '통합 분류1', '통합 분류2', '통합 분류3', '특성추출'],
      dtype='object')

In [33]:
df_test.drop(columns=['개체명(기업기관)',
                      '개체명(인물)',
                      '개체명(지역)',
                      '사건_사고 분류1',
                      '사건_사고 분류2',
                      '사건_사고 분류3',
                      '통합 분류2',
                      '통합 분류3'
                     ], inplace=True)
df_test[:2]

,기고자,본문,언론사,원본주소,일자,제목,주소,키워드,통합 분류1,특성추출
0,당직자공용 기자,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,헤럴드경제,http://biz.heraldcorp.com/view.php?ud=20200201...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명",사회>의료_건강,"신종코,추가,환자,확진"
1,이상규,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,매일경제,http://news.mk.co.kr/newsRead.php?no=104142&ye...,2020-02-01,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시",사회>의료_건강,"접촉자,신종코,감시,확진,검사,속보"

In [34]:
df_test['기고자'][:2]

0    당직자공용 기자
1         이상규
Name: 기고자, dtype: object

In [35]:
df_test['본문'][:2]

0    [헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...
1    [속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...
Name: 본문, dtype: object

In [36]:
df_test.to_csv('covid_news.csv', encoding='utf8')

In [37]:
df_test2 = pd.read_csv('covid_news.csv', encoding='utf8')
df_test2[:5]

,Unnamed: 0,기고자,본문,언론사,원본주소,일자,제목,주소,키워드,통합 분류1,특성추출
0,0,당직자공용 기자,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,헤럴드경제,http://biz.heraldcorp.com/view.php?ud=20200201...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명",사회>의료_건강,"신종코,추가,환자,확진"
1,1,이상규,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,매일경제,http://news.mk.co.kr/newsRead.php?no=104142&ye...,2020-02-01,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시",사회>의료_건강,"접촉자,신종코,감시,확진,검사,속보"
2,2,황재희,[그래픽=연합뉴스] 신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으...,아주경제,http://www.ajunews.com/view/20200201134957462,2020-02-01,[속보] 신종 코로나 확진자 12명…70명 검사 중,http://www.bigkinds.or.kr/news/newsDetailView....,"신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검...",사회>의료_건강,"확진자,코로나바이러스,코로,검사,신종,확인,사람"
3,3,이미경(capital);,[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명 이미경 한경닷컴 기자...,한국경제,https://www.hankyung.com/society/article/20200...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명",사회>의료_건강,"확진환자,1명,6명,신종코,추가,환자,확진,속보,하루"
4,4,김봄이,'신종코로나' 확진환자 1명 추가…국내 총 12명,매일신문,https://news.imaeil.com/Society/20200201094318...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명",사회>의료_건강,"신종코,추가,환자,확진"

In [38]:
df_test2.drop(columns='Unnamed: 0', inplace=True)
df_test2[:2]

,기고자,본문,언론사,원본주소,일자,제목,주소,키워드,통합 분류1,특성추출
0,당직자공용 기자,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,헤럴드경제,http://biz.heraldcorp.com/view.php?ud=20200201...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명",사회>의료_건강,"신종코,추가,환자,확진"
1,이상규,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,매일경제,http://news.mk.co.kr/newsRead.php?no=104142&ye...,2020-02-01,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시",사회>의료_건강,"접촉자,신종코,감시,확진,검사,속보"

In [39]:
df_test3 = pd.DataFrame(total_row, columns = [
                        'title',
                        'content',
                        'field',
                        'date',
                        'addr',
                        'company'
                        ]) #[[row],[],[],[],[]]
df_test3[:2]

,title,content,field,date,addr,company
0,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,사회>의료_건강,2020-02-01,http://biz.heraldcorp.com/view.php?ud=20200201...,헤럴드경제
1,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,사회>의료_건강,2020-02-01,http://news.mk.co.kr/newsRead.php?no=104142&ye...,매일경제

In [40]:
df_test3.shape

(1000, 6)

In [41]:
df_test3.to_csv('covid-total-list.csv', encoding='utf8')

In [42]:
df_test4 = pd.read_csv('covid-total-list.csv', encoding='utf8')
df_test4[:2]

,Unnamed: 0,title,content,field,date,addr,company
0,0,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,사회>의료_건강,2020-02-01,http://biz.heraldcorp.com/view.php?ud=20200201...,헤럴드경제
1,1,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,사회>의료_건강,2020-02-01,http://news.mk.co.kr/newsRead.php?no=104142&ye...,매일경제

In [43]:
df_test4.drop(columns='Unnamed: 0', inplace=True)
df_test4[:2]

,title,content,field,date,addr,company
0,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,사회>의료_건강,2020-02-01,http://biz.heraldcorp.com/view.php?ud=20200201...,헤럴드경제
1,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,사회>의료_건강,2020-02-01,http://news.mk.co.kr/newsRead.php?no=104142&ye...,매일경제

In [44]:
df_test4

,title,content,field,date,addr,company
0,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,사회>의료_건강,2020-02-01,http://biz.heraldcorp.com/view.php?ud=20200201...,헤럴드경제
1,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,사회>의료_건강,2020-02-01,http://news.mk.co.kr/newsRead.php?no=104142&ye...,매일경제
2,[속보] 신종 코로나 확진자 12명…70명 검사 중,[그래픽=연합뉴스] 신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으...,사회>의료_건강,2020-02-01,http://www.ajunews.com/view/20200201134957462,아주경제
3,[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어,[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명 이미경 한경닷컴 기자...,사회>의료_건강,2020-02-01,https://www.hankyung.com/society/article/20200...,한국경제
4,[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명,'신종코로나' 확진환자 1명 추가…국내 총 12명,사회>의료_건강,2020-02-01,https://news.imaeil.com/Society/20200201094318...,매일신문
...,...,...,...,...,...,...
995,"중수본 “동선 공개 늦다? 당사자 기억 의존 NO, 모든 기록 확인”",중앙사고수습본부(중수본)가 6일 신종 코로나바이러스 감염증(신종 코로나) 확진자 동...,사회>사회일반,2020-02-06,http://news.kmib.co.kr/article/view.asp?arcid=...,국민일보
996,"충남대병원, 7일부터 신종 코로나바이러스 신속검사 실시",[충청투데이 선정화 기자] 충남대병원는 오는 7일부터 신종 코로나바이러스 감염증 신...,사회>사회일반,2020-02-06,http://www.cctoday.co.kr/news/articleView.html...,충청투데이
997,[인제]신종 코로나 확산 우려 `모여라 딩동댕' 연기,【인제】신종 코로나바이러스 확산 우려로 오는 19일에 예정됐던 ..`EBS 모여라 ...,사회>사회일반,2020-02-07,http://www.kwnews.co.kr/nView.asp?s=501&aid=22...,강원일보
998,"[e파주소식] 따뜻한 겨울, 변화된 대응 市, 환경기초시설 해빙기 대비 안전점검",파주시는 지난 3일부터 6일까지 관내 환경기초시설을 대상으로 해빙기 대비 안전 점검...,사회>사회일반,2020-02-07,www.joongboo.com/news/articleView.html?idxno=3...,중부일보
999,신종코로나로 주택공급 위축 우려...단기 영향 크지 않아,"신종 코로나바이러스 감염증이 주택공급 위축 우려가 있지만, 단기적으로는 영향이 크지...",사회>사회일반,2020-02-07,https://www.ytn.co.kr/_ln/0102_202002071539372446,YTN